# Generated by Django 3.2.3 on 2021-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20210520_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_history',
            name='bot_chat',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
